-- Eager install (vim.pack.add is idempotent after first install)
vim.pack.add({ 'https://github.com/folke/trouble.nvim' })
require("trouble").setup({})

vim.keymap.set("n", "<leader>xx", function() require("trouble").toggle("diagnostics") end, { desc = "Diagnostics (Trouble)" })
vim.keymap.set("n", "<leader>xX", function() require("trouble").toggle({ mode = "diagnostics", filter = { buf = 0 } }) end, { desc = "Buffer Diagnostics (Trouble)" })
vim.keymap.set("n", "<leader>xs", function() require("trouble").toggle({ mode = "symbols", focus = false }) end, { desc = "Symbols (Trouble)" })
vim.keymap.set("n", "<leader>xl", function() require("trouble").toggle({ mode = "lsp", focus = false, win = { position = "right" } }) end, { desc = "LSP Definitions / References (Trouble)" })
vim.keymap.set("n", "<leader>xL", function() require("trouble").toggle("loclist") end, { desc = "Location List (Trouble)" })
vim.keymap.set("n", "<leader>xQ", function() require("trouble").toggle("qflist") end, { desc = "Quickfix List (Trouble)" })
